"""add home feed columns

Revision ID: 31529fb4eb1a
Revises: 
Create Date: 2026-07-30 18:34:58.830467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31529fb4eb1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.add_column('doctor', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('doctor', sa.Column('specialization', sa.String(length=120), nullable=True))
    op.add_column('doctor', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('post', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'post', 'doctor', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.add_column('question', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('is_anonymous', sa.Boolean(), nullable=True))
    op.add_column('question', sa.Column('is_resolved', sa.Boolean(), nullable=True))
    op.add_column('question', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'question', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'question', 'doctor', ['doctor_id'], ['id'])
    op.add_column('user', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'avatar_url')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'created_at')
    op.drop_column('question', 'is_resolved')
    op.drop_column('question', 'is_anonymous')
    op.drop_column('question', 'doctor_id')
    op.drop_column('question', 'user_id')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'created_at')
    op.drop_column('post', 'likes_count')
    op.drop_column('post', 'image_url')
    op.drop_column('post', 'doctor_id')
    op.drop_column('post', 'user_id')
    op.drop_column('doctor', 'created_at')
    op.drop_column('doctor', 'specialization')
    op.drop_column('doctor', 'is_verified')
    op.drop_column('doctor', 'avatar_url')
    # ### end Alembic commands ###
